IMAGE_TAG_CONFIG_SERVER: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:config-server-qa-v-b"
IMAGE_TAG_DISCOVERY_SERVER: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:discovery-server-qa-v-b"
IMAGE_TAG_CUSTOMERS_SERVICE: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:customers-service-qa-v-b"
IMAGE_TAG_VISITS_SERVICE: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:visits-service-qa-v-b"
IMAGE_TAG_VETS_SERVICE: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:vets-service-qa-v-b"
IMAGE_TAG_API_GATEWAY: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:api-gateway-qa-v-b"
IMAGE_TAG_ADMIN_SERVER: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:admin-server-qa-v-b"
IMAGE_TAG_HYSTRIX_DASHBOARD: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:hystrix-dashboard-qa-v-b"
IMAGE_TAG_GRAFANA_SERVICE: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:grafana-service"
IMAGE_TAG_PROMETHEUS_SERVICE: "867217663272.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo-aa/petclinic-app-qa:prometheus-service"
DNS_NAME: "petclinic.awsaakcay.com"
